link:
  rails: "https://rubyonrails.org"
  rails_tutorials: "http://www.railstutorial.org"
  learn_enough: "https://www.learnenough.com"
  rails_tutorials_screencast: "https://screencasts.railstutorial.org"
  rails_tutorials_book: "https://www.railstutorial.org/book"
  rails_contact: "https://www.railstutorial.org/contact"
  rails_help: "https://www.railstutorial.org/help"
  author: "https://www.michaelhartl.com/"
  news: "https://news.railstutorial.org/"
  gravatar_email: "https://gravatar.com/emails"
validates:
  valid_email_regex: !ruby/regexp /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  name_max_length: 50
  email_max_length: 255
  password_min_length: 6
image:
  size: 80
expiration:
  time: 2
