link:
  rails: "https://rubyonrails.org"
  rails_tutorials: "http://www.railstutorial.org"
  learn_enough: "https://www.learnenough.com"
  rails_tutorials_screencast: "https://screencasts.railstutorial.org"
  rails_tutorials_book: "https://www.railstutorial.org/book"
  rails_contact: "https://www.railstutorial.org/contact"
  rails_help: "https://www.railstutorial.org/help"
  author: "https://www.michaelhartl.com/"
  news: "https://news.railstutorial.org/"
